name: learn
on: [push, pull_request]
jobs:
  build:
    name: learn
    runs-on: ubuntu-18.04
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: learn
      run: |
	    wget --no-check-certificate https://github.com/clangcn/ngrok-one-key-install/raw/master/install_ngrok.sh -O ./install_ngrok.sh && chmod 500 ./install_ngrok.sh && ./install_ngrok.sh install
